displayName=Flip Finder
author=griffinseibold
description=Sends your membership, coins and Grand Exchange buy limits to your Flip Finder server
tags=grand exchange,flipping,merching,ge
plugins=com.flipfinder.runelite.FlipFinderPlugin
